# ucdv_vent_infrastructure "Platform for collecting, aggregating, and storing ventilator data"
# Copyright (C) 2017 Gregory Rehm
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: Creating groups
  group: name="{{item}}"
  with_items: groups_to_create
  tags: ['users','groups','configuration']

- name: Per-user group creation
  group: name="{{item.username}}" gid="{{item.gid if item.gid is defined else item.uid}}"
  with_items: users
  when: users_create_per_user_group
  tags: ['users','configuration']

- name: User creation
  user: name="{{item.username}}"
        group="{{item.username if users_create_per_user_group
            else users_group}}"
        groups="{{item.groups | join(',')}}"
        shell={{item.shell if item.shell is defined else users_default_shell}}
        password="{{item.password if item.password is defined else '!'}}"
        comment="{{item.name}}"
        uid="{{item.uid}}"
        createhome="{{'yes' if users_create_homedirs else 'no'}}"
  with_items: users
  tags: ['users','configuration']

- name: SSH keys
  authorized_key: user="{{item.0.username}}" key='{{item.1}}'
  with_subelements:
    - users
    - ssh_key
  tags: ['users','configuration']

- name: Deleted user removal
  user: name="{{item.username}}" state=absent
  with_items: users_deleted
  tags: ['users','configuration']

- name: Deleted per-user group removal
  group: name="{{item.username}}" state=absent
  with_items: users_deleted
  when: users_create_per_user_group
  tags: ['users','configuration']
