# ucdv_vent_infrastructure "Platform for collecting, aggregating, and storing ventilator data"
# Copyright (C) 2017 Gregory Rehm
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: create retriever user
  user: name=retriever shell=/bin/sh

- name: Create clinicalsupervisor dir
  file: path={{ ansible_distribution|get_clinicalsupervisor_dir }}/clinicalsupervisor state=directory
  tags:
    - clinicalsupervisor

- name: copy clinicalsupervisor source dist
  copy:
    src=clinicalsupervisor-{{ clinicalsupervisor_version }}.tar.gz
    dest={{ ansible_distribution|get_clinicalsupervisor_dir }}/clinicalsupervisor
  tags:
    - clinicalsupervisor
  notify:
    - restart clinicalsupervisor

- name: setup virtualenv
  command: /usr/local/bin/virtualenv venv chdir={{ ansible_distribution|get_clinicalsupervisor_dir }}/clinicalsupervisor
  tags:
    - clinicalsupervisor

- name: install clinicalsupervisor
  command: ./venv/bin/pip install --upgrade clinicalsupervisor-{{ clinicalsupervisor_version }}.tar.gz chdir={{ ansible_distribution|get_clinicalsupervisor_dir }}/clinicalsupervisor
  tags:
    - clinicalsupervisor

- name: retriever should own clinicalsupervisor
  file: path={{ ansible_distribution|get_clinicalsupervisor_dir }}/clinicalsupervisor owner=retriever recurse=yes
  tags:
    - clinicalsupervisor
  notify:
    - restart clinicalsupervisor

- name: Create logdir
  file: path=/var/log/clinicalsupervisor state=directory owner=retriever
  tags:
    - clinicalsupervisor

- name: Create config dir
  file: path=/etc/clinicalsupervisor state=directory owner=retriever
  tags:
    - clinicalsupervisor

- name: Setup app config
  template: src=clinicalsupervisor-app.conf dest=/etc/clinicalsupervisor/clinicalsupervisor.conf
  tags:
    - clinicalsupervisor
  notify:
    - restart clinicalsupervisor

- name: Setup uwsgi config
  template: src=uwsgi.ini dest=/etc/clinicalsupervisor
  tags:
    - clinicalsupervisor
  notify:
    - restart clinicalsupervisor

- name: Install latest rsync
  macports: name=rsync
  when: ansible_distribution == 'MacOSX'
  tags:
    - backups

- name: Setup rpi directories
  file:
    dest={{ ansible_distribution|find_home_dir_root }}/retriever/Data/{{ item }}
    state=directory
    owner=retriever
    group=retriever
  with_items: groups['rpis']
  tags:
    - backups

- name: Execute backup on rpis
  cron:
    name="backup data files onto server for {{ item }}"
    minute={{ item|set_backup_crontab_minute }}
    job="/opt/local/bin/rsync -re 'ssh {{ rsync_ssh_options }}' backup@{{ item|get_rpi_ip_addr(hostname_map=static_dns) }}:/home/pi/Data/* {{ ansible_distribution|find_home_dir_root }}/retriever/Data/{{ item }}"
    user=retriever
  with_items: groups['rpis']
  sudo: yes
  tags:
    - backups
