# ucdv_vent_infrastructure "Platform for collecting, aggregating, and storing ventilator data"
# Copyright (C) 2017 Gregory Rehm
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---

- name: Install brew prereqs
  homebrew: name={{ item }}
  sudo: no
  with_items:
    - mysql
    - python
  when: ansible_distribution == 'MacOSX'
  tags:
    - clinicalsupervisor

- name: ensure pip is locateable in /usr/local/sbin due to ansible bug
  file: src=/usr/local/bin dest=/usr/local/sbin state=link
  when: ansible_distribution == 'MacOSX'
  tags:
    - clinicalsupervisor

- name: Install supervisor
  pip: name=supervisor
  when: ansible_distribution == 'MacOSX'
  tags:
    - clinicalsupervisor
  notify:
    - start supervisor OSX

- name: Install apt prerequisites
  apt:
    name={{ item }}
  with_items:
    - nginx
    - rsync
    - python-pip
    - mysql-server
    - libmysqlclient-dev
    - supervisor
  when: ansible_os_family == 'Debian'
  tags:
    - clinicalsupervisor

- name: Install common pip packages
  pip: name={{ item }}
  with_items:
    - MySQL-python
    - virtualenv
  tags:
    - clinicalsupervisor
