# ucdv_vent_infrastructure "Platform for collecting, aggregating, and storing ventilator data"
# Copyright (C) 2017 Gregory Rehm
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---

- name: Create supervisor dirs
  file: dest=/etc/supervisor/conf.d state=directory
  tags:
    - clinicalsupervisor

- name: Setup supervisord main config
  copy: dest=/etc/supervisor/ src=supervisord.conf
  tags:
    - clinicalsupervisor
  when: ansible_distribution == 'MacOSX'

- name: setup launchd config file
  copy: dest="/Library/LaunchDaemons/com.b2c.supervisord.plist" src=launchd-supervisor.conf
  tags:
    - clinicalsupervisor
  notify:
    - load launchd file
  when: ansible_distribution == 'MacOSX'

# XXX needs a task for linux

- name: Setup clinicalsupervisor supervisord config
  template: src=clinicalsupervisor-supervisor.conf dest=/etc/supervisor/conf.d/clinicalsupervisor.conf
  tags:
    - clinicalsupervisor
  notify:
    - restart clinicalsupervisor

- name: register supervisor app
  supervisorctl: name=clinicalsupervisor state=present config=/etc/supervisor/supervisord.conf supervisorctl_path=/usr/local/bin/supervisorctl
  tags:
    - clinicalsupervisor
