- name: setup sshd_config
  copy: src=sshd_config dest=/etc/ssh/

- name: setup users vimrc
  copy:
    src=vimrc
    dest=/home/{{ item.username }}/.vimrc
    owner={{ item.username }}
  tags: ['users', 'configuration']
  with_items: users|if_bash

- name: setup users bashrc
  copy:
    src=bashrc
    dest=/home/{{ item.username }}/.bashrc
    owner={{ item.username }}
  tags: ['users', 'configuration']
  with_items: users|if_bash
