# ucdv_vent_infrastructure "Platform for collecting, aggregating, and storing ventilator data"
# Copyright (C) 2017 Gregory Rehm
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

- name: setup backup user
  user: name=backup shell=/bin/false

- name: setup backup ssh dir
  file: path=/home/backup/.ssh state=directory

- name: setup cleaner user
  user: name=cleaner shell=/bin/false

- name: setup cleaner ssh dir
  file: path=/home/cleaner/.ssh state=directory

- name: setup lister user
  user: name=lister shell=/bin/false

- name: setup lister ssh dir
  file: path=/home/lister/.ssh state=directory

- name: setup backup ssh auth keys
  template: src=backup_auth_keys.j2 dest=/home/backup/.ssh/authorized_keys

- name: setup cleaner ssh auth keys
  template: src=cleaner_auth_keys.j2 dest=/home/cleaner/.ssh/authorized_keys

- name: setup lister ssh auth keys
  template: src=lister_auth_keys.j2 dest=/home/lister/.ssh/authorized_keys

- name: setup /etc/hostname
  hostname: name={{ inventory_hostname }}
  when: change_hostnames
  tags:
    - configuration
    - hostname

- name: copy rsync package
  copy: src=rsync_3.1.1-3_armhf.deb dest=/var/tmp
  tags:
    - configuration
    - rsync

- name: install rsync
  apt:
    deb: /var/tmp/rsync_3.1.1-3_armhf.deb
  tags:
    - configuration
    - rsync
