# ucdv_vent_infrastructure "Platform for collecting, aggregating, and storing ventilator data"
# Copyright (C) 2017 Gregory Rehm
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: Setup gwf
  copy: src=gwf dest=/etc/init.d/ mode=0744
  tags:
    - scripts
    - gwf

- name: Enable gwf at startup
  service: name=gwf enabled=yes
  tags:
    - scripts
    - gwf

- name: setup gwf.py script
  copy: src=gwf.py dest=/home/pi/gwf.py
  tags:
    - scripts
    - gwf

- name: extract setuptools
  unarchive:
    src: setuptools-36.3.0.zip
    dest: /home/pi/
  tags:
    - scripts
    - gwf

- name: install setuptools
  shell: "python setup.py install"
  args:
    chdir: /home/pi/setuptools-36.3.0/
  tags:
    - scripts
    - gwf

- name: copy pip to machine
  copy: src=pip-9.0.1.tar.gz dest=/home/pi
  tags:
    - scripts
    - gwf

- name: install pip
  shell: easy_install /home/pi/pip-9.0.1.tar.gz
  tags:
    - scripts
    - gwf

- name: copy pyserial to machine
  copy: src=pyserial-3.4-py2.py3-none-any.whl dest=/home/pi
  tags:
    - scripts
    - gwf

- name: install pyserial
  pip: name=file:///home/pi/pyserial-3.4-py2.py3-none-any.whl
  tags:
    - scripts
    - gwf

- name: copy six to machine
  copy: src=six-1.11.0-py2.py3-none-any.whl dest=/home/pi
  tags:
    - scripts
    - gwf
    - testing
    - get_serial

- name: install six
  pip: name=file:///home/pi/six-1.11.0-py2.py3-none-any.whl
  tags:
    - scripts
    - gwf
    - testing
    - get_serial

- name: copy pbr to machine
  copy: src=pbr-4.0.2-py2.py3-none-any.whl dest=/home/pi
  tags:
    - scripts
    - gwf
    - testing
    - get_serial

- name: install pbr
  pip: name=file:///home/pi/pbr-4.0.2-py2.py3-none-any.whl
  tags:
    - scripts
    - gwf
    - testing
    - get_serial

- name: copy pbr to machine
  copy: src=funcsigs-1.0.2-py2.py3-none-any.whl dest=/home/pi
  tags:
    - scripts
    - gwf
    - testing
    - get_serial

- name: install pbr
  pip: name=file:///home/pi/funcsigs-1.0.2-py2.py3-none-any.whl
  tags:
    - scripts
    - gwf
    - testing
    - get_serial

- name: copy mock to machine
  copy: src=mock-2.0.0-py2.py3-none-any.whl dest=/home/pi
  tags:
    - scripts
    - gwf
    - testing
    - get_serial

- name: install mock
  pip: name=file:///home/pi/mock-2.0.0-py2.py3-none-any.whl
  tags:
    - scripts
    - gwf
    - testing
    - get_serial

- name: ensure we rotate logs
  copy: src=logrotate dest=/etc/logrotate.d/gwf
  tags:
    - scripts
    - gwf

- name: Setup get_serial configuration dir
  file: path=/etc/b2c state=directory owner=pi group=pi
  tags:
    - scripts
    - get_serial

- name: Setup get_serial prod configuration file
  template: src={{ item }} dest=/etc/b2c/ owner=pi group=pi
  with_items:
    - script_config
    - script_testing_config
  tags:
    - scripts
    - get_serial
    - testing

- name: Setup get_serial
  copy: src=get_serial.py dest=/home/pi/ mode=0644 owner=pi group=pi
  tags:
    - scripts
    - get_serial

- name: copy socat package
  copy: src=socat_1.7.2.4-2_armhf.deb dest=/var/tmp
  tags:
    - configuration
    - testing
    - get_serial

- name: install socat
  apt:
    deb: /var/tmp/socat_1.7.2.4-2_armhf.deb
  tags:
    - configuration
    - testing
    - get_serial

- name: copy tests
  copy: src=test_data_integration.py dest=/home/pi
  tags:
    - configuration
    - testing
    - get_serial

- name: run tests
  shell: python /home/pi/test_data_integration.py
  tags:
    - configuration
    - testing
    - get_serial
