---
- name: Setup gwf
  copy: src=gwf dest=/etc/init.d/ mode=0744
  tags:
    - scripts
    - gwf

- name: Enable gwf at startup
  service: name=gwf enabled=yes
  tags:
    - scripts
    - gwf

- name: setup gwf.py script
  copy: src=gwf.py dest=/home/pi/gwf.py
  tags:
    - scripts
    - gwf

- name: ensure we rotate logs
  copy: src=logrotate dest=/etc/logrotate.d/gwf
  tags:
    - scripts
    - gwf

- name: Setup get_serial configuration dir
  file: path=/etc/b2c state=directory owner=pi group=pi
  tags:
    - scripts
    - get_serial

- name: Setup get_serial prod configuration file
  template: src={{ item }} dest=/etc/b2c/ owner=pi group=pi
  with_items:
    - script_config
    - script_testing_config
  tags:
    - scripts
    - get_serial

- name: Setup get_serial
  copy: src=get_serial.py dest=/home/pi/ mode=0644 owner=pi group=pi
  tags:
    - scripts
    - get_serial
