#!/bin/bash
# /etc/init.d/getwaveform

### BEGIN INIT INFO
# Provides:          getwaveform
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon to get waveform from ventilator
# Description:       This script is just an init.d wrapper around gwf.py
### END INIT INFO

case "$1" in
    start)
        python /home/pi/gwf.py
        ;;
    stop)
        killall python
        ;;
    restart)
        killall python
        python /home/pi/gwf.py
        ;;
    *)
        echo "Usage: /etc/init.d/gwf start|stop|restart"
        exit 1
        ;;
esac

exit 0
